MOCO-477: Playing around with pagination for useCollection.
mojitoinc/hooks pull request #35
Opened 2022-07-08 11:14 UTC by Danziger

2022-07-08 11:15 UTC, Danziger commented on src/hooks/useCollection/useCollection.ts
> +      force: true,
@MisaGu Is this working properly? Do I need some additional prop or dep so that this query is re-fetched every time a variable (`page` or `pageSize`) is updated?

2022-07-08 11:21 UTC, Danziger commented on codegen.yaml
> -  src\domain\interfaces\mojito-schema.interface.ts:
This was creating a file named `"src\domain\interfaces\mojito-schema.interface.ts"` instead of following that directory structure.

2022-07-08 12:58 UTC, Danziger commented on src/hooks/useCollectionPage/useCollectionPage.ts
> +    [collectionSlug, marketplaceID, props.page, props.pageSize],
@MisaGu Is this working properly inside `useMojitoFactory`? Do I need some additional prop or dep so that this query is re-fetched every time a variable (page or pageSize) is updated?

2022-07-08 14:05 UTC, Danziger commented on src/hooks/useCollection/useCollection.ts
> +    [collectionSlug, marketplaceID, paginationArgs?.offset, paginationArgs?.limit],
@MisaGu Is this working properly inside useMojitoFactory? Do I need some additional prop or dep so that this query is re-fetched every time a variable (page or pageSize) is updated?

2022-07-12 11:40 UTC, ekuznetski commented on src/domain/interfaces/hooks.interface.ts
> +  pageSize?: number;
i recommend to rename _pageSize_ to _itemsPerPage_

2022-07-12 12:26 UTC, Danziger commented on src/domain/interfaces/hooks.interface.ts
> +  pageSize?: number;
Updated. Give me 2 minutes to address something else.

2022-07-12 12:35 UTC, Danziger commented on src/hooks/useCollection/demo/demo1.tsx
> +    const itemCount = (result?.collection as unknown as DevSchema.MarketplaceCollection)
Normalized types still use production generated types, so if we want to use something that is only in DEV, we can cast it like this. Once this change is promoted to PROD, we simply remove the casting.

2022-07-12 12:36 UTC, MisaGu requested changes

2022-07-12 12:36 UTC, MisaGu commented on src/domain/utils/paginationUtils.ts
> +  if (props.page === undefined) return undefined;
```suggestion
export function getPaginationArgs({page = 1, pageSize}: PaginatedQueryProps): PaginationArgs | undefined {
  if (page < 1) return undefined;
```

2022-07-12 12:41 UTC, Danziger commented on src/hooks/useMojitoFactory/useMojitoFactory.tsx
> +      keepPreviousData: options?.keepPreviousData ?? variables?.page !== undefined,
If you are requesting paginated content, you don't want to go back to the loading state every time you change the page. `keepPreviousData` will make `useQuery` return the "old" page while the new one is being fetched.

2022-07-12 12:54 UTC, Danziger commented on src/hooks/useCollection/useCollection.ts
> +    [paginationArgs?.offset, paginationArgs?.limit],
It doesn't, I've just tried with your change and changing the page in the demo doesn't do anything.

2022-07-13 10:02 UTC, Danziger commented on src/domain/utils/paginationUtils.ts
> +    offset: (page - 1) * itemsPerPage,
Pagination indexes start at 1 now.

2022-07-13 17:00 UTC, merged